name: nodd
desc: Nodd 2.0 is a new version of Official SCJ Discord Bot. Nodd bot is originally for Numbering Server members, but now has integrated functions.
version: 2.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  gsheets: ^0.3.2
  nyxx: ^2.0.5
  nyxx_interactions: ^2.0.2
  pointycastle: ^3.4.0
dev_dependencies:
  lints: ^1.0.1
  test: ^1.18.2
